apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: content-block-manager-jwt-auth-secret
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Secret key for encrypting/decrypting JWT authentication tokens for
      content-block-manager to allow non-signon users to access a block's preview
      for Factcheck.
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
    name: content-block-manager-jwt-auth-secret
  dataFrom:
    - extract:
        key: govuk/content-block-manager/jwt-auth-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
