apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mirror-drift-detection-slack-webhook
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Slack webhook used to alert when drift is detected
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
    name: mirror-drift-detection-slack-webhook
  dataFrom:
    - extract:
        key: govuk/mirror/slack-webhook
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
