apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows-read-only
subjects:
  - kind: ServiceAccount
    name: argo-workflows-read-only
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-read-write
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows-read-write
subjects:
  - kind: ServiceAccount
    name: argo-workflows-read-write
    namespace: {{ .Release.Namespace }}
