apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: support-aws
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      AWS secrets belonging to Support.
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: support-aws
  dataFrom:
    - extract:
        key: govuk/support/aws
