apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: anonymous-user-id
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Shared secret for anonymising user ids, as per signon ADR 001
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
    name: anonymous-user-id
  dataFrom:
    - extract:
        key: govuk/publishing/anonymous_user_id_secret
