apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fact-check-manager-postgres
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Credentials for Fact check manager's Postgres DB hosted in RDS.
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
    name: fact-check-manager-postgres
    template:
      data:
        DATABASE_URL: '{{ $.Files.Get "externalsecrets-templates/psql-conn-string.tpl" | trim }}/fact-check-manager_production'
  dataFrom:
    - extract:
        key: govuk/fact-check-manager/postgres
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
