apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: support-api-zendesk
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Zendesk API access token for Support API
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
    name: support-api-zendesk
  dataFrom:
    - extract:
        key: govuk/support-api/zendesk
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
