# TODO: do we even still need to create secret/argocd-notifications-secret in
# both namespaces? If not, get rid of this and remove ClusterExternalSecret
# from the list of allowed resource types in
# charts/argo-bootstrap/templates/argocd/govuk-project.yaml
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: argocd-notifications-secret
  labels:
    argocd.argoproj.io/secret-type: argocd-notifications-secret
spec:
  externalSecretName: "argocd-notifications-secret"
  namespaceSelector:
    matchExpressions:
      - {key: kubernetes.io/metadata.name, operator: In, values: [apps, cluster-services]}
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secretsmanager
      kind: ClusterSecretStore
    target:
      template:
        metadata:
          labels:
            argocd.argoproj.io/secret-type: argocd-notifications-secret
        data:
          # Helm and External Secrets use the same template language and conflict
          slack_url: "{{
            "{{ .slackUrl | toString}}"
          }}"
          argo_events_webhook_token: "{{
            "{{ .argoEventsWebhookToken | toString}}"
          }}"
          grafana_api_key: "{{
            "{{ .grafanaApiKey | toString}}"
          }}"
    data:
      - secretKey: slackUrl
        remoteRef:
          key: govuk/slack-webhook-url
          property: url
      - secretKey: argoEventsWebhookToken
        remoteRef:
          key: govuk/argo-events-webhook-token
          property: token
      - secretKey: grafanaApiKey
        remoteRef:
          key: govuk/argo-notifications/grafana
          property: grafana-api-key
