apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: whitehall-mysql
  labels:
    {{- include "govuk-apps-conf.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Credentials for Whitehall to connect to MYSQL.
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: whitehall-mysql
    template:
      data:
        DATABASE_URL: '{{ $.Files.Get "externalsecrets-templates/mysql-conn-string.tpl" | trim }}/whitehall_production'
  dataFrom:
    - extract:
        key: govuk/whitehall/mysql-primary
