{{- if .Values.uploadFrontendErrorPagesEnabled }}
{{- $fullName := include "generic-govuk-app.fullname" . }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-upload-error-pages
  labels:
    {{- include "generic-govuk-app.labels" . | nindent 4 }}
    app: {{ $fullName }}-upload-error-pages
    app.kubernetes.io/name: {{ $fullName }}-upload-error-pages
    app.kubernetes.io/component: upload-error-pages
  annotations:
    argocd.argoproj.io/hook: PostSync
    kubernetes.io/description: >
      Fetch "static" error pages from the Frontend app and upload them to S3.
      ArgoCD runs this job after each deployment of the Frontend app.
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 1
  template:
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot | default "true" }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: upload-frontend-error-pages
          image: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/github/alphagov/govuk/toolbox:latest
          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation | default "false" }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem | default "true" }}
            capabilities:
              drop: ["ALL"]
          env:
            - name: GOVUK_ENVIRONMENT
              value: {{ .Values.govukEnvironment }}
            - name: SERVICE
              value: {{ $fullName }}
          command:
            - "/bin/bash"
            - "-c"
            - |
              {{- .Files.Get "upload-frontend-error-pages.sh" | nindent 14 }}
          {{- with .Values.jobResources }}
          resources:
            {{- . | toYaml | trim | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      restartPolicy: Never
      {{- if eq "arm64" .Values.arch }}
      tolerations:
        - key: arch
          operator: Equal
          value: {{ .Values.arch }}
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/arch: {{ .Values.arch }}
      {{- end }}
{{- end }}
