{{- if .Values.nginxConfigMap.create }}
{{- $fullName := include "generic-govuk-app.fullname" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-nginx-conf
  labels:
    {{- include "generic-govuk-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
data:
  nginx.conf: |-

    error_log  /dev/stderr warn;
    pid        /tmp/nginx.pid;

    load_module /usr/lib/nginx/modules/ngx_http_perl_module.so;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp_path;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;

      proxy_buffer_size 16k;  # Max total size of response headers.
      # n * m = max response size before spooling to disk. p95 response size should
      # fit comfortably within this in order to avoid performance issues.
      proxy_buffers 24 16k;

      server_tokens off;

      sendfile        on;
      keepalive_timeout  65;

      # Set GOVUK-Request-Id if not set
      # See http://nginx.org/en/docs/http/ngx_http_perl_module.html
      perl_modules perl/lib;
      perl_set $govuk_request_id '
        sub {
          my $r = shift;
          my $current_header = $r->header_in("GOVUK-Request-Id");
          if (defined $current_header && $current_header ne "") {
            return $current_header;
          } else {
            my $pid = $r->variable("pid");
            my $msec = $r->variable("msec");
            my $remote_addr = $r->variable("remote_addr");
            my $request_length = $r->variable("request_length");
            return "$pid-$msec-$remote_addr-$request_length";
          }
        }
      ';

      # This map creates a $sts_default variable for later use.
      # If this header is already set by upstream, then $sts_default will
      # be an empty string, which will later lead to:
      #    add_header Strict-Transport-Security ''
      # which will be ignored according to http://serverfault.com/a/598106
      # If the header is not set by upstream, then $sts_default will be set
      # and later uses in add_header will be effective.
      map $upstream_http_strict_transport_security $sts_default {
       '' "max-age=31536000; preload";
      }

      log_format json_event '{ "@timestamp": "$time_iso8601", '
                           '"body_bytes_sent": $body_bytes_sent, '
                           '"bytes_sent": $bytes_sent, '
                           '"govuk_dependency_resolution_source_content_id": "$http_govuk_dependency_resolution_source_content_id", '
                           '"govuk_original_url": "$http_govuk_original_url", '
                           '"govuk_request_id": "$http_govuk_request_id", '
                           '"gzip_ratio": "$gzip_ratio", '
                           '"http_host": "$http_host", '
                           '"http_referer": "$http_referer", '
                           '"http_user_agent": "$http_user_agent", '
                           '"http_x_forwarded_for": "$http_x_forwarded_for", '
                           '"remote_addr": "$remote_addr", '
                           '"remote_user": "$remote_user", '
                           '"request": "$request", '
                           '"request_query_string": "$query_string", '
                           '"request_method": "$request_method", '
                           '"request_time": $request_time, '
                           '"request_uri": "$request_uri", '
                           '"sent_http_content_type": "$sent_http_content_type", '
                           '"sent_http_location": "$sent_http_location", '
                           '"sent_http_x_cache": "$sent_http_x_cache", '
                           '"server_name": "$server_name", '
                           '"server_port": "$server_port", '
                           '"server_protocol": "$server_protocol", '
                           '"ssl_cipher": "$ssl_cipher", '
                           '"ssl_protocol": "$ssl_protocol", '
                           '"status": $status, '
                           '"upstream_addr": "$upstream_addr", '
                           '"upstream_response_time": "$upstream_response_time" }';

      upstream {{ $fullName }} {
        server 127.0.0.1:{{ .Values.appPort }};
      }

      server {
        listen {{ .Values.nginxPort }};
        proxy_connect_timeout {{ .Values.nginxProxyConnectTimeout }};
        proxy_read_timeout    {{ .Values.nginxProxyReadTimeout }};

        access_log /dev/stdout json_event;
        error_log /dev/stderr;

        add_header Strict-Transport-Security $sts_default;
        add_header Permissions-Policy interest-cohort=();
        proxy_set_header GOVUK-Request-Id $govuk_request_id;
        add_header X-Content-Type-Options "nosniff" always;

        {{- if ( or (ne .Values.govukEnvironment "production") (eq .Values.nginxDenyCrawlers true ) ) }}
        add_header X-Robots-Tag "noindex";
        {{- end }}

        location / {
          proxy_set_header   Host $http_host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_pass         http://{{ $fullName }};
          proxy_redirect     off;
        }

{{- if .Values.serveRailsAssetsFromFilesystem }}
        location /assets {
          alias /assets/;
          autoindex off;
        }
{{- else if .Values.proxyRailsAssetsToS3 }}
        location /assets {
          proxy_set_header   Authorization "";
          proxy_set_header   Connection "";
          proxy_set_header   X-Real-IP $remote_addr;  # TODO: pass the actual end-client address
          proxy_hide_header  x-amz-id-2;
          proxy_hide_header  x-amz-meta-server-side-encryption;
          proxy_hide_header  x-amz-request-id;
          proxy_hide_header  x-amz-server-side-encryption;
          proxy_hide_header  x-amz-version-id;
          add_header         Cache-Control max-age=31536000;
          proxy_intercept_errors on;
          proxy_pass         https://govuk-app-assets-{{ .Values.govukEnvironment }}.s3.eu-west-1.amazonaws.com;

          location ~ "-[0-9a-f]{32,}\." {
            expires max;
            add_header Cache-Control "public, immutable";
            add_header Surrogate-Key "assets assets-{{ $fullName }}";
            proxy_pass https://govuk-app-assets-{{ .Values.govukEnvironment }}.s3.eu-west-1.amazonaws.com;

            # Set CORS allow origin for fonts only
            location ~* \.(eot|otf|ttf|woff|woff2)$ {
              add_header Access-Control-Allow-Origin "*";
              add_header Access-Control-Allow-Methods "GET, OPTIONS";
              add_header Access-Control-Allow-Headers "origin, authorization";
              proxy_pass https://govuk-app-assets-{{ .Values.govukEnvironment }}.s3.eu-west-1.amazonaws.com;
            }
          }
        }
{{- end }}

        # Endpoint that isn't cached, which is used to assert that an external
        # service can receive a response from GOV.UK origin on www hostname. It
        # is intended for pingdom monitoring
        location = /__canary__ {
          default_type application/json;
          add_header cache-control "max-age=0,no-store,no-cache";
          return 200 '{"message": "Tweet tweet"}\n';
        }

        # Endpoint for liveness and readiness checks of the nginx container.
        location = /readyz {
          return 200 'ok\n';
        }
        {{- if .Values.nginxConfigMap.extraConf }}
        {{ .Values.nginxConfigMap.extraConf | nindent 8 }}
        {{- end }}
      }
    }
{{- end }}
