apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: set-automatic-deploys-enabled
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
  - name: set-automatic-deploys-enabled
    eventSourceName: webhook
    eventName: set-automatic-deploys-enabled
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        namespace: {{ .Values.workflowsNamespace }}
        parameters:
          - dest: spec.arguments.parameters.0.value
            src:
              dependencyName: set-automatic-deploys-enabled
              dataKey: body.environment
          - dest: spec.arguments.parameters.1.value
            src:
              dependencyName: set-automatic-deploys-enabled
              dataKey: body.repoName
          - dest: spec.arguments.parameters.2.value
            src:
              dependencyName: set-automatic-deploys-enabled
              dataKey: body.imageTag
          - dest: spec.arguments.parameters.3.value
            src:
              dependencyName: set-automatic-deploys-enabled
              dataKey: body.automaticDeploysEnabled
          - dest: metadata.generateName
            src:
              dependencyName: set-automatic-deploys-enabled
              dataKey: body.repoName
            operation: prepend
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: -set-automatic-deploys-enabled-
              namespace: {{ .Values.workflowsNamespace }}
            spec:
              arguments:
                parameters:
                  - name: environment
                  - name: repoName
                  - name: imageTag
                  - name: automaticDeploysEnabled
              workflowTemplateRef:
                name: set-automatic-deploys-enabled
