{{- $fullName := include "mirror.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "mirror.labels" . | nindent 4 }}
    app: {{ $fullName }}
    app.kubernetes.io/component: app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        {{- include "mirror.labels" . | nindent 8 }}
        app: {{ $fullName }}
        app.govuk/repository-name: {{ .Values.repoName | default .Release.Name  }}
        app.kubernetes.io/component: app
    spec:
      {{- if .Values.serviceAccount.enabled }}
      automountServiceAccountToken: true
      serviceAccountName: {{ .Values.serviceAccount.name | default $fullName }}
      {{- else }}
      automountServiceAccountToken: false
      {{- end }}
      enableServiceLinks: false
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 12 }}
      containers:
        - name: app
          image: {{ .Values.appImage.repository }}:{{ .Values.appImage.tag }}
          command: ["/bin/govuk-mirror-resp-status-check"]
          imagePullPolicy: {{ .Values.appImage.pullPolicy | default "Always" }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 16 }}
          env:
            - name: MIRROR_AVAILABILITY_URL
              value: https://www.{{ .Values.externalDomainSuffix }}
            - name: STATUS_CHECK_REFRESH_INTERVAL
              value: "4h"
            {{- with .Values.extraEnv }}
              {{- (tpl (toYaml .) $) | trim | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet: &probe
              path: /metrics
              port: metrics
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 30
          readinessProbe:
            httpGet: *probe
            failureThreshold: 2
            periodSeconds: 5
            timeoutSeconds: 30
          startupProbe:
            httpGet: *probe
            failureThreshold: 15
            periodSeconds: 2
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if eq "arm64" .Values.arch }}
      tolerations:
        - key: arch
          operator: Equal
          value: {{ .Values.arch }}
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/arch: {{ .Values.arch }}
      {{- end }}
