---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "mirror.fullname" . }}"
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
  labels:
    {{- include "mirror.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.mirrorSchedule }}"
  jobTemplate:
    metadata:
      name: "{{ include "mirror.fullname" . }}"
      labels:
        {{- include "mirror.labels" . | nindent 8 }}
    spec:
      backoffLimit: 0
      template:
        metadata:
          name: "{{ include "mirror.fullname" . }}"
          labels:
            {{- include "mirror.labels" . | nindent 12 }}
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        spec:
          enableServiceLinks: false
          serviceAccountName: {{ include "mirror.serviceAccountName" . }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          restartPolicy: Never
          volumes:
            - name: app-mirror-sync
              persistentVolumeClaim:
                claimName: {{ include "mirror.fullname" . }}
            - name: app-tmp
              emptyDir: {}
          containers:
            - name: scrape
              image: {{ .Values.appImage.repository }}:{{ .Values.appImage.tag }}
              imagePullPolicy: "Always"
              workingDir: /data
              resources:
                limits:
                  cpu: 4
                  memory: 20000Mi
                requests:
                  cpu: 2
                  memory: 15000Mi
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              volumeMounts:
                - name: app-mirror-sync
                  mountPath: /data
                - name: app-tmp
                  mountPath: /tmp
              env:
                - name: SITE
                  value: 'https://www.{{ .Values.externalDomainSuffix }}/sitemap.xml'
                - name: ALLOWED_DOMAINS
                  value: 'www.{{ .Values.externalDomainSuffix }},{{ .Values.assetsDomain }}'
                - name: DISALLOWED_URL_RULES
                  value: '/apply-for-a-licence(/|$),/business-finance-support(/|$),/drug-device-alerts\.atom,/drug-safety-update\.atom,/foreign-travel-advice\.atom,/government/announcements\.atom,/government/publications\.atom,/government/statistics\.atom,/licence-finder/,/search(/|$),\.csv/preview$'
                - name: CONCURRENCY
                  value: "5"
                - name: METRIC_REFRESH_INTERVAL
                  value: "10s"
                - name: RATE_LIMIT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "mirror.fullname" . }}
                      key: rate-limit-token
                - name: HEADERS
                  value: 'rate-limit-token:$(RATE_LIMIT_TOKEN)'
                - name: PROMETHEUS_PUSHGATEWAY_URL
                  valueFrom:
                    configMapKeyRef:
                      name: govuk-apps-env
                      key: PROMETHEUS_PUSHGATEWAY_URL
                - name: MIRROR_FRESHNESS_URL
                  value: https://www.{{ .Values.externalDomainSuffix }}/last-updated.txt
                - name: MIRROR_AVAILABILITY_URL
                  value: https://www.{{ .Values.externalDomainSuffix }}
                - name: AWS_REGION
                  value: eu-west-2
                - name: S3_BUCKET_NAME
                  value: govuk-{{ .Values.govukEnvironment }}-mirror
                {{- with .Values.extraEnv }}
                  {{- (tpl (toYaml .) $) | trim | nindent 16 }}
                {{- end }}
