apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontend-elections-api
  labels:
    {{- include "govuk-apps-conf.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Credentials used by Frontend to access external Elections API service
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: frontend-elections-api
  dataFrom:
    - extract:
        key: govuk/frontend/elections-api
