apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: manuals-publisher-link-checker-api-callback-token
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Manuals publisher uses this for verification of batch-completion webhook
      (i.e. callback) requests from Link Checker API. See
      https://github.com/alphagov/link-checker-api/blob/main/docs/api.md#verifying-the-webhook-request
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: manuals-publisher-link-checker-api-callback-token
  dataFrom:
    - extract:
        key: govuk/manuals-publisher/link-checker-api-callback-token
