apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: govuk-dex-argocd
  namespace: {{ .Values.clusterServicesNamespace }}
  labels:
    app.kubernetes.io/part-of: argocd
  annotations:
    kubernetes.io/description: >
      This secret contains the OAUTH secret which allows ArgoCD to
      authenticate with Dex (https://dexidp.io/), a federated
      OpenID connect provider
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: govuk-dex-argocd
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: govuk/dex/argocd
