apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: govuk-ci-github-creds
  namespace: {{ .Values.appsNamespace }}
  annotations:
    kubernetes.io/description: >
       Personal access token for govuk-ci GitHub user
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: govuk-ci-github-creds
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: govuk/github/govuk-ci
