apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: slack-webhook-url
  namespace: {{ .Values.appsNamespace }}
  annotations:
    kubernetes.io/description: >
      This secret contains the slack webhook to post on Slack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: slack-webhook-url
    creationPolicy: Owner
  dataFrom:
  - key: govuk/slack-webhook-url
