apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: feedback-notify
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      The GOV.UK Notify API key belonging to Feedback.
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
    name: feedback-notify
  dataFrom:
    - extract:
        key: govuk/feedback/notify
