apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "repositories": [
        "alphagov/govuk-helm-charts",
        "alphagov/govuk-infrastructure",
        "alphagov/govuk-fastly",
        "alphagov/govuk-fastly-secrets",
        "alphagov/terraform-govuk-infrastructure-sensitive"
      ]
    }
