"alertmanager":
  "alertmanagerSpec":
    "externalUrl": "https://alertmanager.eks.staging.govuk.digital"
    "podAntiAffinity": "hard"
    "podDisruptionBudget":
      "enabled": true
    "replicas": 2
"grafana":
  "env":
    "AWS_ROLE_ARN": "arn:aws:iam::696911096973:role/kube-prometheus-stack-grafana-govuk"
  "grafana.ini":
    "auth.generic_oauth":
      "api_url": "https://dex.eks.staging.govuk.digital/userinfo"
      "auth_url": "https://dex.eks.staging.govuk.digital/auth"
      "role_attribute_path": "contains(groups[*], 'alphagov:gov-uk-production-deploy')
        && 'Admin' || contains(groups[*], 'alphagov:gov-uk') && 'Viewer'"
      "token_url": "https://dex.eks.staging.govuk.digital/token"
    "server":
      "domain": "grafana.eks.staging.govuk.digital"
  "ingress":
    "hosts":
      - "grafana.eks.staging.govuk.digital"
  "replicas": 2
  "serviceAccount":
    "annotations":
      "eks.amazonaws.com/role-arn": "arn:aws:iam::696911096973:role/kube-prometheus-stack-grafana-govuk"
"prometheus":
  "prometheusSpec":
    "externalUrl": "https://prometheus.eks.staging.govuk.digital"
    "podAntiAffinity": "hard"
    "podDisruptionBudget":
      "enabled": true
    "replicas": 2
    "storageSpec":
      "volumeClaimTemplate":
        "spec":
          "resources":
            "requests":
              "storage": "200Gi"
