apiVersion: batch/v1
kind: CronJob
metadata:
  name: govuk-synthetic-test-app-cronjob
  namespace: apps
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
    kubernetes.io/description: >
      This cronjob runs synthetic tests against GOV.UK cluster using a Ginkgo test framework.

      The tests are currently checking that:
      - all running pods in the apps namespace are running with arm64 images.
      - the synthetic test assumed roles have the correct permissions and access according to 
      the environment that they are running in.
spec:
  schedule: "0 11 * * 1-5"
  jobTemplate:
    metadata:
      labels:
        app: govuk-synthetic-test-app-cronjob
        app.kubernetes.io/arch: arm64
    spec:
      template:
        metadata:
          labels:
            app: govuk-synthetic-test-app-cronjob
            app.kubernetes.io/arch: arm64
        spec:
          serviceAccountName: synthetic-test-assumer
          restartPolicy: Never
          containers:
            - name: govuk-synthetic-test-app-cronjob
              image: '172025368201.dkr.ecr.eu-west-1.amazonaws.com/github/alphagov/govuk/govuk-synthetic-test-app:{{ .Values.image_tag }}'
              imagePullPolicy: Always
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          tolerations:
            - key: arch
              operator: Equal
              value: arm64
              effect: NoSchedule
